name: Publish Client

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

env:
  AZURE_WEBAPP_NAME: tvmenukaartclient
  AZURE_WEBAPP_PACKAGE_PATH: "./dist"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          cache-dependency-path: ./package-lock.json
          node-version: 22.1.0
          cache: npm

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          cp web.config dist/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.4.3
        with:
          name: node-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.CLIENT_APP_PUBLISH_PROFILE }}
          package: .